#!/bin/bash

#default_user=$(logname 2>/dev/null || echo ${SUDO_USER:-${USER}})
#HOME="/home/${default_user}"

mkdir -p /home/$(logname)/.config/geany/colorschemes
sudo chmod 777 /home/$(logname)/.config/geany/colorschemes
cd /home/$(logname)/ && git clone https://github.com/geany/geany-themes.git
cp /home/$(logname)/geany-themes/colorschemes/* /home/$(logname)/.config/geany/colorschemes/
rm -rf /home/$(logname)/geany-themes
find /home/$(logname)/.config/geany/colorschemes -type f -exec chmod 777 {} \;


